# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: 17

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build and Package
        run: mvn clean package -DskipTests

      - name: Upload artifact for Deployment job
        uses: actions/upload-artifact@v2
        with:
          name: petclinic-app
          path: '${{ env.ASC_PACKAGE_PATH }}/pet-clinic-web/target/*.jar'

#  deploy:
#    name: Deploy to Azure Cloud
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#      - name: Download artifact from Build job
#        uses: actions/download-artifact@v2
#        with:
#          name: petclinic-app
#
#      - name: Deploy to Azure Webapp
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'milans-petclinic-app'
#          slot-name: 'Production'
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PETCLINICAPP }}
#          package: '*.jar'
